### ISSUE TITLE
Plugin incompatible with MacOS

### ISSUE THREAD

**Issue by kessler-frost** [AgnostiqHQ/covalent-awslambda-plugin#13]
It seems when the client's machine is a Mac the execution fails on lambda with the following error:

```python
[ERROR] ImportError: cannot import name '_psutil_linux' from partially initialized module 'psutil' (most likely due to a circular import) (/var/task/psutil/__init__.py)
Traceback (most recent call last):
  File "/var/task/lambda_function.py", line 18, in lambda_handler
    function, args, kwargs = pickle.load(f)
  File "/var/task/covalent/__init__.py", line 27, in <module>
    from . import executor, leptons
  File "/var/task/covalent/executor/__init__.py", line 35, in <module>
    from .base import BaseExecutor, wrapper_fn
  File "/var/task/covalent/executor/base.py", line 38, in <module>
    from covalent._workflow.depscall import RESERVED_RETVAL_KEY__FILES
  File "/var/task/covalent/_workflow/__init__.py", line 26, in <module>
    from .electron import electron
  File "/var/task/covalent/_workflow/electron.py", line 48, in <module>
    from .lattice import Lattice
  File "/var/task/covalent/_workflow/lattice.py", line 35, in <module>
    import covalent_ui.result_webhook as result_webhook
  File "/var/task/covalent_ui/result_webhook.py", line 26, in <module>
    import covalent_ui.app as ui_server
  File "/var/task/covalent_ui/app.py", line 32, in <module>
    from covalent_dispatcher._service.app_dask import DaskCluster
  File "/var/task/covalent_dispatcher/_service/app_dask.py", line 10, in <module>
    from dask.distributed import LocalCluster
  File "/var/task/dask/distributed.py", line 11, in <module>
    from distributed import *
  File "/var/task/distributed/__init__.py", line 10, in <module>
    from distributed.actor import Actor, ActorFuture, BaseActorFuture
  File "/var/task/distributed/actor.py", line 14, in <module>
    from distributed.client import Future
  File "/var/task/distributed/client.py", line 54, in <module>
    from distributed import cluster_dump, preloading
  File "/var/task/distributed/preloading.py", line 19, in <module>
    from distributed.core import Server
  File "/var/task/distributed/core.py", line 29, in <module>
    from distributed.comm import (
  File "/var/task/distributed/comm/__init__.py", line 46, in <module>
    _register_transports()
  File "/var/task/distributed/comm/__init__.py", line 20, in _register_transports
    from distributed.comm import inproc, ws
  File "/var/task/distributed/comm/ws.py", line 28, in <module>
    from distributed.comm.tcp import (
  File "/var/task/distributed/comm/tcp.py", line 48, in <module>
    from distributed.system import MEMORY_LIMIT
  File "/var/task/distributed/system.py", line 3, in <module>
    import psutil
  File "/var/task/psutil/__init__.py", line 102, in <module>
    from . import _pslinux as _psplatform
  File "/var/task/psutil/_pslinux.py", line 26, in <module>
    from . import _psutil_linux as cext
```

This seems like a pickling issue and should be resolvable if we import some things appropriately in covalent itself.

**Comment by AlejandroEsquivel** [comment]
Fixed by not installing and packaging deps locally
